### ISSUE TITLE
Laptop #2 - Slow WiFi

### ISSUE THREAD

**Issue by Logiqx** [Logiqx/wsw-results#25]
Different brand of WiFi NIC to laptop 1 but I had no end of trouble getting it to recognise minis on the network. It was slow at finding them, sometimes missed them and never recognised when they were disconnected. It would even think they disconnected minis were still on the network, even after a server restart.

I ruled out the NIC by testing with the USB one then was left debugging DNS stuff, resolv.conf, WSL and lots of stuff that frankly, I’d rather not have to deal with.

Manually testing the speed of name resolution:

```sh
 run -it --rm --dns 192.168.0.254 python:3.10-slim-bullseye
Python 3.10.13 (main, Sep 20 2023, 11:28:18) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.getaddrinfo('motion-007', 80, proto=socket.IPPROTO_TCP)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

Long story cut short, I uninstalled the newer version of Docker (4.21.1 / 24.0.2) and installed the older version (4.12.0 / 20.10.17) that was running on laptop 1. I then re-installed all of the Docker images, rebuilt the motion server and everything now works perfectly, just like the laptop 1.

**Comment by Logiqx** [comment]
Closing issue due to fix.

Do not update Docker without testing the Motion server!
